name: Build and Deploy Lambda Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          
      - name: Build and Push Docker image to ECR Public
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t public.ecr.aws/myalias/completely/new:$IMAGE_TAG .
          docker push public.ecr.aws/myalias/completely/new:$IMAGE_TAG

      # Deploy to Lambda using the container image from ECR
      - name: Deploy Lambda Function (Container)
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: my-lambda-function     # Change to your function name
          image-uri: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}   # Points to your newly built image
